export const ERRORS = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CREATE_MESSAGE_PERMISSION_DENIED: 'CREATE_MESSAGE_PERMISSION_DENIED',
  CREATE_CHAT_PERMISSIONS_DENIED: 'CREATE_CHAT_PERMISSIONS_DENIED',
}
